### ISSUE TITLE
印章预览中文乱码

### ISSUE THREAD

**Issue by baggiocq** [kaifangqian/kaifangqian-base#18]
![Uploading 1.jpg…]()

**Comment by baggiocq** [comment]
![1](https://github.com/kaifangqian/kaifangqian-base/assets/18679151/45365a51-f6ee-4a54-9d6c-126a5264b0cf)

**Comment by YoLung** [comment]
您好 怎么解决的乱码问题 是服务器字体缺失吗 windows没问题
